package com.steelypip.powerups.jinxml;

public interface Path {
	
	Element getElement();
	
	String getSelector();
	
	int getPosition();
	
	Path getParent();
	
	default boolean isRoot() { return this.getParent() == null; }
	
	Iterable<Path> generatePaths();
	
	Iterable<Path> generatePaths( final String selector );
	
	/**
	 * Returns true if this path points to an element that has already been generated by a path that shares the
	 * same root path.
	 * @return if the element was earlier generated from the same root
	 */
	boolean isAlreadyGenerated();
	
	/**
	 * Returns true if this path points to an element that has been encountered previously on the same path.
	 * @return if the element is its own ancestor
	 */
	boolean isOwnAncestor();

}
